site_name: HomeGym Documentation
docs_dir: src
copyright: '&copy; Scott Brodersen 2025'
theme:
  name: mkdocs
  user_color_mode_toggle: true
  color_mode: dark
  custom_dir: theme_overrides
nav:
  - Prepare: 'prepare.md'
  - Log: 'track.md'
  - Plan: 'programs.md'
  - Execute: 'instances.md'
  - Analyze: 'analyze.md'
extra_css:
  - style.css
markdown_extensions:
  - extra
